name: 'Terraform'

on:
  pull_request:
    branches:
      - master

env:
  TF_VERSION: 1.3.5
  ARM_SUBSCRIPTION_ID: b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb

jobs:
  terraform:
    name: 'terraform'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Setup providers configuration
        shell: bash
        run: |
          cat << EOF > provider.tf
          provider "azurerm" {
            features {}
          }
          EOF
      - name: Terraform Init
        run: terraform init

      - name: Terraform format
        run: terraform fmt -check

      - name: Terraform validate
        run: terraform validate
